### PR TITLE
[WIP] Message Borads!

### PR DESCRIPTION
**Pull request by samuelh2005**
**What is this?**

This will add those message boards that you see above highways. They come in three colours: green, blue and white!
Currently you cannot type text yet, but you will be able to!

image

**What do you think?** 
Should they go in the "Traffics" tab or the "Signs" tab. They might belong in the "Traffics" tab because they are not localised to the EU. But they might belong in the "Signs" tab because they are also a sign.

**Notes**
Also ignore everything about crafting machines in the git history. I liked how the crafting machine looked and used it in my own mod.
Edit: and it didn't seem to fit the mod's theme.

### CODE REVIEW

**Comment by tismatis** [comment]
I like this idea! I will check your code tomorrow ;)

**Comment by samuelh2005** [comment]
How could I create a `RegisterABlockEntity` function so I can use it in your `RegisterWithClass` function because I can't do it the [normal way](https://fabricmc.net/wiki/tutorial:blockentity), I need to use a `Block Entity` so I can get the text working on the boards.

**Comment by tismatis** [comment]
I check that now and i come back

**Comment by tismatis** [comment]
_You can use the normal way (there are no problem but), i just wanted to made easy all modification for my side_
Okay i commit the modification in like 2min

**Comment by samuelh2005** [comment]
Remember to `git push`!

**Comment by tismatis** [comment]
Pushed! [https://github.com/Matis-Projects/tismatis-roads/commit/61910e92b9b2f7183c8a7a760affb4efa4e87ecc](url) Sorry for the time I take for make that, it's because i didn't used Java these last time...

**Comment by samuelh2005** [comment]
Thansk!

**Comment by samuelh2005** [comment]
image

Now text can be seen on the Message Boards! But it cannot be seen yet!

**Comment by tismatis** [comment]
Problem of sync?

**Comment by samuelh2005** [comment]
I was meant to say cannot be edited!

**Comment by samuelh2005** [comment]
image

Now the font has been made bigger! The colour of the text can be changed like a normal sign, same with glowing text.
But to change text you need to do the `/setblock` command. And the text is saved into NBT data, so it's still there when the world is reloaded.
Edit: But there is not GUI to change the text yet!

**Comment by samuelh2005** [comment]
Current progress on GUI.
image

There is no cursor to say where you are typing, and there are no graphics for highlighting text and the text isn't saved to sign yet.

**Comment by samuelh2005** [comment]
Now the signs are editable! Just need to fix the xray bug.
image

**Comment by samuelh2005** [comment]
@GameursProduction Now everything should be done!

**Comment by tismatis** [comment]
Hi! I check and I merge ;)

**Comment by tismatis** [comment]
Sorry if I take a lot of time to put it in all versions, I have this month a lot of things Todo.

**Pull request merged**
